require('dotenv').config()
const express = require('express')
const indexRoute = require('./routes/index')
const projectRoute = require('./routes/project')
const imageRoute = require('./routes/image')
const errorRoute = require('./routes/error')

module.exports = express()
  .use(express.json())
  .use(express.urlencoded({ extended: true }))

  .use('/', indexRoute)
  .use('/v1/project', projectRoute)
  .use('/v1/image', imageRoute)
  .use(errorRoute)
